/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v2/HotelDetail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search
         * @description Search hotel room rates and available inventory for a specific property, enabling users to view detailed room availability and pricing information.
         */
        post: operations["HotelDetail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/CheckRoomRate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Prebook
         * @description Check the availability and price of a specific room rate selected, usually requested when the user selects a room to book and submits a booking. <br><br>
         */
        post: operations["CheckRoomRate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/CreateOrder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Booking
         * @description Booking
         *
         *     Note: If the request times out, returns a PENDING status, or returns an error, please poll the Retrieve Booking API to obtain the final status of the booking.
         */
        post: operations["CreateOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/CancelOrder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel
         * @description Send a cancel request to cancel refundable and pending bookings.
         *
         *     Note: If the request times out or returns an error, please poll the Retrieve Booking API to obtain the final status of the booking.
         */
        post: operations["CancelOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/SearchOrder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retrieve Booking
         * @description Retrieve booking to check its status in the booking process.
         */
        post: operations["SearchOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/QueryBookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Query Bookings
         * @description Query bookings by date range with pagination. Use this endpoint to retrieve a list of orders filtered by check-in date, check-out date, or booking date. The actual API endpoint is POST /v2/SearchOrder (same URL as Retrieve Booking, but with different request parameters).
         */
        post: operations["QueryBookings"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/HotelStaticList": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Hotel List
         * @description Retrieve static data for hotels.
         */
        post: operations["HotelStaticList"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/RegionList": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Region List
         * @description Retrieve the list of regions.
         */
        post: operations["RegionList"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/RoomStaticList": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Hotel Room Type List
         * @description Retrieve the list of room information of sepecific hotels.
         */
        post: operations["RoomTypeStatic"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "cancelOrder.CancelOrderRequest": {
            /**
             * @description Agent reference ID provided in the CreateOrder request by the agent; maximum length is 128.
             * @example 213415
             */
            AgentRefID?: string;
            RequestHeader?: components["schemas"]["common.RequestHeader"];
        };
        "cancelOrder.CancelOrderResponse": {
            /** @description This value will not be returned if an error occurs. */
            CancelResult?: components["schemas"]["cancelOrder.CancelResult"];
            /** @description This value will be returned if an error occurs. */
            Error?: components["schemas"]["common.Error"];
            ResponseHeader?: components["schemas"]["common.ResponseHeader"];
        };
        "cancelOrder.CancelResult": {
            /**
             * @description Cancellation penalty fee charged.
             * @example 42
             */
            CancelFee?: number;
            /**
             * @description Currency code for the charge amount.
             * @example CNY
             */
            CurrencyCode?: string;
            /**
             * @description Order status. <br><table><tr><th>OrderStatus</th><th>Description</th></tr><tr><td>PENDING</td><td>Booking confirmation pending.</td></tr><tr><td>CONFIRMED</td><td>Booking confirmed.</td></tr><tr><td>CANCELLED</td><td>Booking cancelled.</td></tr><tr><td>FAILED</td><td>Booking confirmation failed.</td></tr></table>
             * @example CANCELLED
             */
            OrderStatus?: string;
        };
        "common.Error": {
            /**
             * @description Error code. <br><table><tr><th>ErrorCode</th><th>Description</th></tr><tr><td>101</td><td>No payload in the request.</td></tr><tr><td>102</td><td>Invalid format of the request.</td></tr><tr><td>103</td><td>Request data validation failed.</td></tr><tr><td>104</td><td>Service error.</td></tr><tr><td>105</td><td>API user authentication error; invalid AgentCode, Username, or Password.</td></tr></table>
             * @example 101
             */
            ErrorCode?: string;
            /**
             * @description Error message.
             * @example invaild param
             */
            ErrorMessage?: string;
        };
        "common.RequestHeader": {
            /**
             * @description Unique code for the agent provided by TourMind.
             * @example tms_test
             */
            AgentCode?: string;
            /**
             * @description Password for the API request.
             * @example tms_test
             */
            Password?: string;
            /**
             * @description Request timestamp in ISO 8601 format with millisecond precision, e.g., "2006-01-02T15:04:05.123Z".
             * @example 2018-07-26T09:51:32.123Z
             */
            RequestTime?: string;
            /**
             * @description Identifier for tracing API requests, such as using a GUID.
             * @example 6ba7b810-9dad-11d1-80b4-00c04fd430c8
             */
            TransactionID?: string;
            /**
             * @description Username for the API request.
             * @example tms_test
             */
            UserName?: string;
        };
        "common.ResponseHeader": {
            /**
             * @description Response timestamp, format: “2006-01-02 15:04:05”.
             * @example 2018-07-26 09:51:32
             */
            ResponseTime?: string;
            /**
             * @description This value must match the TransactionID in the request..
             * @example 6ba7b810-9dad-11d1-80b4-00c04fd430c8
             */
            TransactionID?: string;
        };
        "createOrder.ContactInfo": {
            /**
             * @description Email of the booking contact.
             * @example xxx@google.com
             */
            Email?: string;
            /**
             * @description First Name of the booking contact.
             * @example Tom
             */
            FirstName?: string;
            /**
             * @description Last Name of the booking contact.
             * @example Lee
             */
            LastName?: string;
            /**
             * @description Phone number of the booking contact.
             * @example 1521777777
             */
            PhoneNo?: string;
        };
        "createOrder.CreateOrderRequest": {
            /**
             * @description Unique agent reference ID to identify a booking; maximum length is 128 characters. Note! Reserving with the same AgentRefID will not create a new reservation; instead, the original reservation information will be returned.
             * @example 213415
             */
            AgentRefID?: string;
            /**
             * @description Check-in date, format: “2006-01-02”.
             * @example 2018-08-15
             */
            CheckIn?: string;
            /**
             * @description Check-out date, format: “2006-01-02”.
             * @example 2018-08-18
             */
            CheckOut?: string;
            /** @description Contact information for the booking. */
            ContactInfo?: components["schemas"]["createOrder.ContactInfo"];
            /**
             * @description Currency code.
             * @example CNY
             */
            CurrencyCode?: string;
            /**
             * @description TourMind Hotel ID; only one ID is required in this request.
             * @example 235113
             */
            HotelCode?: number;
            /** @description Request room occupancies. Note: Currently, only the same number of adults and children is supported for each room; for multiple rooms, you only need to fill in one object. */
            PaxRooms?: components["schemas"]["createOrder.PaxRoom"][];
            /**
             * @description TourMind Rate ID.
             * @example 2132151
             */
            RateCode?: string;
            RequestHeader?: components["schemas"]["common.RequestHeader"];
            /**
             * @description Special customer requests.
             * @example Non-smoking room
             */
            SpecialRequest?: string;
            /**
             * @description Total price for the booking returned from the CheckRoomRateResponse.
             * @example 88.88
             */
            TotalPrice?: number;
        };
        "createOrder.CreateOrderResponse": {
            /** @description This value will be returned if an error occurs. */
            Error?: components["schemas"]["common.Error"];
            /** @description This value will not be returned if an error occurs. */
            OrderInfo?: components["schemas"]["createOrder.OrderInfo"];
            /**
             * @description Tourmind order ID
             * @example 10470379
             */
            ReservationID?: string;
            ResponseHeader?: components["schemas"]["common.ResponseHeader"];
        };
        "createOrder.OrderInfo": {
            /**
             * @description Order status. <br><table><tr><th>OrderStatus</th><th>Description</th></tr><tr><td>PENDING</td><td>Booking confirmation pending.</td></tr><tr><td>CONFIRMED</td><td>Booking confirmed.</td></tr><tr><td>CANCELLED</td><td>Booking cancelled.</td></tr><tr><td>FAILED</td><td>Booking confirmation failed.</td></tr></table>
             * @example CONFIRMED
             */
            OrderStatus?: string;
            /**
             * @description Tourmind order ID
             * @example 10470379
             */
            ReservationID?: string;
        };
        "createOrder.PaxName": {
            /** @example Tom */
            FirstName?: string;
            /** @example Lee */
            LastName?: string;
            /**
             * @description ADU represents Adult, CHI represents Child.
             * @example ADU
             */
            Type?: string;
        };
        "createOrder.PaxRoom": {
            /** @example 2 */
            Adults?: number;
            /** @example 0 */
            Children?: number;
            /** @description Children's ages; the count of the array must equal the number of children. */
            ChildrenAges?: number[];
            PaxNames?: components["schemas"]["createOrder.PaxName"][];
            /** @example 1 */
            RoomCount?: number;
        };
        "hotelDetail.CancelPolicyInfo": {
            /** @description Cancellation charge amount. */
            Amount?: number;
            /** @description Currency for the cancellation charge amount. */
            CurrencyCode?: string;
            /** @description Cancellation policy window end, format: “2006-01-02“. */
            EndDateTime?: string;
            /** @description Specific start time, format: "2006-01-02 15:04:05" */
            From?: string;
            /** @description Cancellation policy window start, format: "2006-01-02". */
            StartDateTime?: string;
            /** @description Specific end time, format: "2006-01-02 15:04:05" */
            To?: string;
        };
        "hotelDetail.DailyPriceInfo": {
            /** @description this is daily inventory count */
            Count?: number;
            /** @description Date, format: "2006-01-02" */
            Date?: string;
            /** @description Price for 1 room per night. */
            Price?: number;
        };
        "hotelDetail.Hotel": {
            /**
             * @description Check-in date, format: “2006-01-02”.
             * @example 2018-08-25
             */
            CheckIn?: string;
            /**
             * @description Check-out date, format: “2006-01-02”.
             * @example 2018-08-26
             */
            CheckOut?: string;
            /**
             * @description Hotel code.
             * @example 740650
             */
            HotelCode?: string;
            /** @description Room types available based on the search criteria. */
            RoomTypes?: components["schemas"]["hotelDetail.RoomType"][];
        };
        "hotelDetail.HotelDetailRequest": {
            /**
             * @description Check-in date, format: “2006-01-02”.
             * @example 2018-08-25
             */
            CheckIn?: string;
            /**
             * @description Check-out date, format: “2006-01-02”.
             * @example 2018-08-26
             */
            CheckOut?: string;
            /** @description TourMind hotel IDs; up to 20 IDs are supported in this request. */
            HotelCodes?: number[];
            /** @description If true, daily price information will be included in the response. Default: false. */
            IsDailyPrice?: boolean;
            /**
             * @description Nationality.
             * @example CN
             */
            Nationality?: string;
            /** @description Request room occupancies. Note: Currently, only the same number of adults and children is supported for each room; for multiple rooms, you only need to fill in one object. */
            PaxRooms?: components["schemas"]["hotelDetail.PaxRoomRQ"][];
            /**
             * @description request timeout, millisecond
             * @example 6000
             */
            Timeout?: number;
            RequestHeader?: components["schemas"]["common.RequestHeader"];
        };
        "hotelDetail.HotelDetailResponse": {
            /** @description This value will be returned if an error occurs. */
            Error?: components["schemas"]["common.Error"];
            /** @description Hotel information. */
            Hotels?: components["schemas"]["hotelDetail.Hotel"][];
            ResponseHeader?: components["schemas"]["common.ResponseHeader"];
        };
        "hotelDetail.MealInfo": {
            /**
             * @description Number of free meals offered.
             * @example 2
             */
            MealCount?: number;
            /**
             * @description Meal type <br><table><tr><th>MealType</th><th>Description</th></tr><tr><td>1</td><td>No Breakfast</td></tr><tr><td>2</td><td>Breakfast</td></tr><tr><td>3</td><td>Lunch</td></tr><tr><td>4</td><td>Dinner</td></tr><tr><td>5</td><td>Lunch and Dinner</td></tr><tr><td>6</td><td>HalfBoard</td></tr><tr><td>7</td><td>FullBoard</td></tr><tr><td>8</td><td>AllInclusive</td></tr><tr><td>9</td><td>SelfCatering</td></tr></table>
             * @example breakfast
             */
            MealType?: string;
        };
        "hotelDetail.PaxRoomRQ": {
            /**
             * @description Number of adults per room.
             * @example 4
             */
            Adults?: number;
            /**
             * @description Number of children per room.
             * @example 0
             */
            Children?: number;
            /** @description Children's ages; the count of the array must equal the number of children. */
            ChildrenAges?: number[];
            /**
             * @description Room count.
             * @example 2
             */
            RoomCount?: number;
        };
        "hotelDetail.RateInfo": {
            /**
             * @description Available room inventory count.
             * @example 2
             */
            Allotment?: number;
            /** @description Cancellation policy information. */
            CancelPolicyInfos?: components["schemas"]["hotelDetail.CancelPolicyInfo"][];
            /**
             * @description Currency code.
             * @example CNY
             */
            CurrencyCode?: string;
            /** @description Daily pricing information for the hotel. */
            DailyPriceInfo?: components["schemas"]["hotelDetail.DailyPriceInfo"][];
            /** @description Invoice information: 1: Hotel invoice, 2: TourMind invoice */
            InvoiceInfo?: number;
            /** @description Meal information. */
            MealInfo?: components["schemas"]["hotelDetail.MealInfo"];
            /**
             * @description Sub-room name, i.e. the original room name from the supplier/hotel system. More accurate than the aggregated name in RoomType, but results in more static room entries. In rare cases, sub-rooms may be incorrectly mapped to their parent room type.
             * @example SUITE THREE BEDROOMS
             */
            Name?: string;
            /** @description Sub-room name in Chinese, i.e. the original room name from the supplier/hotel system. More accurate than the aggregated name in RoomType, but results in more static room entries. In rare cases, sub-rooms may be incorrectly mapped to their parent room type. */
            NameCN?: string;
            /**
             * @description Rate identifier for a sellable product; this code is unique across all TourMind hotels.
             * @example 13800206
             */
            RateCode?: string;
            Refundable?: boolean;
            /**
             * @description Total price; this is the total amount charged.
             * @example 688.88
             */
            TotalPrice?: number;
            /** @description Bed type description. */
            bedTypeDesc?: string;
            /** @description Bed type description in Chinese. */
            bedTypeDescCN?: string;
        };
        "hotelDetail.RoomType": {
            /** @description Bed type description. */
            BedTypeDesc?: string;
            /** @description Bed type description in Chinese. */
            BedTypeDescCN?: string;
            /**
             * @description Aggregated room type name, cleaner and easier to display, recommended. Note: in rare cases, it may differ from the sub-room name in RateInfo.
             * @example Suite 3 bedrooms
             */
            Name?: string;
            /**
             * @description Aggregated room type name in Chinese, cleaner and easier to display, recommended. Note: in rare cases, it may differ from the sub-room name in RateInfo.
             * @example Triple Room
             */
            NameCN?: string;
            /** @description A list of rates for a room type; at least one rate will be returned. */
            RateInfos?: components["schemas"]["hotelDetail.RateInfo"][];
            /**
             * @description TourMind room type code, which is a unique identifier across all TourMind hotels.
             * @example 4613
             */
            RoomTypeCode?: string;
        };
        "hotelstatic.HotelInfo": {
            /**
             * @description Hotel address.
             * @example 3007 Santa Monica Blvd, 90404
             */
            Address?: string;
            /** @description Hotel address in Chinese. */
            Address_CN?: string;
            /**
             * @description City code.,Matched region ID.
             * @example 14209
             */
            CityCode?: string;
            /**
             * @description City name.
             * @example ShangHai
             */
            CityName?: string;
            /**
             * @description City name in Chinese.
             * @example Shanghai
             */
            CityNameCN?: string;
            /**
             * @description Country code.，ISO 3166-1 alpha-2, e.g., China: CN.
             * @example CN
             */
            CountryCode?: string;
            /**
             * @description TourMind hotel ID.
             * @example 739315
             */
            HotelId?: string;
            Images?: components["schemas"]["hotelstatic.Image"][];
            /**
             * @description Latitude.
             * @example 34.03644
             */
            Latitude?: string;
            /**
             * @description Longitude.
             * @example -118.47048
             */
            Longitude?: string;
            /**
             * @description Hotel name.
             * @example Days Inn Santa Monica/Los Angeles
             */
            Name?: string;
            /** @description Hotel name in Chinese. */
            Name_CN?: string;
            /**
             * @description Hotel phone number.
             * @example 1523333333
             */
            Phone?: string;
            /**
             * @description Hotel star rating.
             * @example 5
             */
            StarRating?: string;
        };
        "hotelstatic.HotelStaticListRequest": {
            /**
             * @description Country code.
             * @example CN
             */
            CountryCode?: string;
            /** @description Identifiers for specific hotels.. */
            HotelIds?: number[];
            /** @description Pagination information. */
            Pagination?: components["schemas"]["hotelstatic.Pagination"];
            RequestHeader?: components["schemas"]["common.RequestHeader"];
        };
        "hotelstatic.HotelStaticListResponse": {
            /** @description This value will be returned if an error occurs. */
            Error?: components["schemas"]["common.Error"];
            /** @description This value will not be returned if an error occurs. */
            HotelStaticListResult?: components["schemas"]["hotelstatic.HotelStaticListResult"];
            ResponseHeader?: components["schemas"]["common.ResponseHeader"];
        };
        "hotelstatic.HotelStaticListResult": {
            /** @description Hotel information. */
            Hotels?: components["schemas"]["hotelstatic.HotelInfo"][];
            /** @description Pagination information. */
            Pagination?: components["schemas"]["hotelstatic.PaginationRS"];
        };
        "hotelstatic.Image": {
            caption?: string;
            category?: number;
            hero_image?: boolean;
            links?: {
                [key: string]: components["schemas"]["hotelstatic.Link"];
            };
        };
        "hotelstatic.Link": {
            href?: string;
            method?: string;
        };
        "hotelstatic.Pagination": {
            /**
             * @description PageIndex needs to accommodate both string and integer types. [1 or '1']
             * @example 1
             */
            PageIndex?: unknown;
            /**
             * @description Items per page.
             * @example 10
             */
            PageSize?: number;
        };
        "hotelstatic.PaginationRS": {
            /**
             * @description Total number of pages.
             * @example 1
             */
            PageCount?: number;
            /**
             * @description Total number of records.
             * @example 10
             */
            TotalCount?: number;
        };
        "regionList.Region": {
            /**
             * @description ISO 3166-1 alpha-2, e.g., China: CN.,
             * @example 231
             */
            CountryCode?: string;
            /**
             * @description Region name.
             * @example ShangHai
             */
            Name?: string;
            /**
             * @description Region name in Chinese. (Nullable.)
             * @example Shanghai
             */
            NameCN?: string;
            /**
             * @description TourMind region ID.
             * @example 21312541
             */
            RegionID?: string;
            /**
             * @description Region name
             * @example Shanghai, China
             */
            RegionNameLong?: string;
            /**
             * @description Full region name in Chinese.
             * @example Shanghai, China
             */
            RegionNameLongCN?: string;
        };
        "regionList.RegionListRequest": {
            /**
             * @description Country code.
             * @example CN
             */
            CountryCode?: string;
            RequestHeader?: components["schemas"]["common.RequestHeader"];
        };
        "regionList.RegionListResponse": {
            Error?: components["schemas"]["common.Error"];
            RegionListResult?: components["schemas"]["regionList.RegionListResult"];
            ResponseHeader?: components["schemas"]["common.ResponseHeader"];
        };
        "regionList.RegionListResult": {
            Regions?: components["schemas"]["regionList.Region"][];
        };
        "roomAvail.CancelPolicyInfo": {
            /** @description Cancellation charge amount. */
            Amount?: number;
            /** @description Currency for the cancellation charge amount. */
            CurrencyCode?: string;
            /** @description Cancellation policy window end, format: “2006-01-02“. */
            EndDateTime?: string;
            /** @description Specific start time, format: "2006-01-02 15:04:05" */
            From?: string;
            /** @description Cancellation policy window start, format: "2006-01-02". */
            StartDateTime?: string;
            /** @description Specific end time, format: "2006-01-02 15:04:05" */
            To?: string;
        };
        "roomAvail.DailyPriceInfo": {
            /** @description this is daily inventory count */
            Count?: number;
            /** @description Date, format: "2006-01-02" */
            Date?: string;
            /** @description Price of a specific date. */
            Price?: number;
        };
        "roomAvail.DateRange": {
            /** @description End date of low price period */
            End?: string;
            /** @description Start date of low price period */
            Start?: string;
        };
        "roomAvail.Hotel": {
            /**
             * @description Check-in date, format: “2006-01-02”.
             * @example 2018-08-25
             */
            CheckIn?: string;
            /**
             * @description Check-out date, format: “2006-01-02”.
             * @example 2018-08-26
             */
            CheckOut?: string;
            /**
             * @description Hotel code.
             * @example 740650
             */
            HotelCode?: string;
            LowPricePeriod?: components["schemas"]["roomAvail.LowPricePeriod"];
            /** @description Room types available based on the search criteria. */
            RoomTypes?: components["schemas"]["roomAvail.RoomType"][];
        };
        "roomAvail.LowPricePeriod": {
            /** @description Current price of the hotel */
            CurrentPrice?: number;
            DateRange?: components["schemas"]["roomAvail.DateRange"];
            LowPriceRange?: components["schemas"]["roomAvail.LowPriceRange"];
            /** @description Last update time of the price prediction */
            UpdateTime?: string;
        };
        "roomAvail.LowPriceRange": {
            /** @description Currency code for the prices */
            CurrencyCode?: string;
            /** @description Maximum price in the range */
            Max?: number;
            /** @description Minimum price in the range */
            Min?: number;
        };
        "roomAvail.MealInfo": {
            /**
             * @description Number of free meals offered.
             * @example 2
             */
            MealCount?: number;
            /**
             * @description Meal type <br><table><tr><th>MealType</th><th>Description</th></tr><tr><td>1</td><td>No Breakfast</td></tr><tr><td>2</td><td>Breakfast</td></tr></table>
             * @example breakfast
             */
            MealType?: string;
        };
        "roomAvail.PaxRoomRQ": {
            /**
             * @description Number of adults per room.
             * @example 4
             */
            Adults?: number;
            /**
             * @description Number of children per room.
             * @example 0
             */
            Children?: number;
            /** @description Children's ages; the count of the array must equal the number of children. */
            ChildrenAges?: number[];
            /**
             * @description Room count.
             * @example 2
             */
            RoomCount?: number;
        };
        "roomAvail.RateInfo": {
            /**
             * @description Available room inventory count.
             * @example 2
             */
            Allotment?: number;
            /** @description Cancellation policy information. */
            CancelPolicyInfos?: components["schemas"]["roomAvail.CancelPolicyInfo"][];
            /**
             * @description Currency code.
             * @example CNY
             */
            CurrencyCode?: string;
            /** @description Daily pricing information for the hotel. */
            DailyPriceInfo?: components["schemas"]["roomAvail.DailyPriceInfo"][];
            /** @description Meal information. */
            MealInfo?: components["schemas"]["roomAvail.MealInfo"];
            /**
             * @description Sub-room name, i.e. the original room name from the supplier/hotel system. More accurate than the aggregated name in RoomType, but results in more static room entries. In rare cases, sub-rooms may be incorrectly mapped to their parent room type.
             * @example SUITE THREE BEDROOMS
             */
            Name?: string;
            /** @description Sub-room name in Chinese, i.e. the original room name from the supplier/hotel system. More accurate than the aggregated name in RoomType, but results in more static room entries. In rare cases, sub-rooms may be incorrectly mapped to their parent room type. */
            NameCN?: string;
            /**
             * @description Rate identifier for a sellable product; this code is unique across all TourMind hotels.
             * @example 13800206
             */
            RateCode?: string;
            Refundable?: boolean;
            /**
             * @description Total price; this is the total amount charged.
             * @example 688.88
             */
            TotalPrice?: number;
            /** @description Bed type description. */
            bedTypeDesc?: string;
            /** @description Bed type description in Chinese. */
            bedTypeDescCN?: string;
        };
        "roomAvail.RoomAvailRequest": {
            /**
             * @description Check-in date, format: “2006-01-02”.
             * @example 2018-08-25
             */
            CheckIn?: string;
            /**
             * @description Check-out date, format: “2006-01-02”.
             * @example 2018-08-26
             */
            CheckOut?: string;
            /** @description TourMind Hotel ID; only one ID is required in this request. */
            HotelCodes?: number[];
            /**
             * @description Nationality.
             * @example CN
             */
            Nationality?: string;
            /** @description Request room occupancies. Note: Currently, only the same number of adults and children is supported for each room. */
            PaxRooms?: components["schemas"]["roomAvail.PaxRoomRQ"][];
            /**
             * @description TourMind Rate ID.
             * @example 13800206
             */
            RateCode?: string;
            RequestHeader?: components["schemas"]["common.RequestHeader"];
        };
        "roomAvail.RoomAvailResponse": {
            /** @description This value will be returned if an error occurs. */
            Error?: components["schemas"]["common.Error"];
            /** @description Hotel information. */
            Hotels?: components["schemas"]["roomAvail.Hotel"][];
            ResponseHeader?: components["schemas"]["common.ResponseHeader"];
        };
        "roomAvail.RoomType": {
            /** @description Bed type description. */
            BedTypeDesc?: string;
            /** @description Bed type description in Chinese. */
            BedTypeDescCN?: string;
            /**
             * @description Aggregated room type name, cleaner and easier to display, recommended. Note: in rare cases, it may differ from the sub-room name in RateInfo.
             * @example Suite 3 bedrooms
             */
            Name?: string;
            /**
             * @description Aggregated room type name in Chinese, cleaner and easier to display, recommended. Note: in rare cases, it may differ from the sub-room name in RateInfo.
             * @example Triple Room
             */
            NameCN?: string;
            /** @description A list of rates for a room type; at least one rate will be returned. */
            RateInfos?: components["schemas"]["roomAvail.RateInfo"][];
            /**
             * @description TourMind room type code, which is a unique identifier across all TourMind hotels.
             * @example 4613
             */
            RoomTypeCode?: string;
        };
        "roomStatic_model.RoomStaticRequest": {
            /**
             * @description Hotel.Code
             * @example 235113
             */
            HotelCode?: number;
            RequestHeader?: components["schemas"]["common.RequestHeader"];
        };
        "roomStatic_model.RoomStaticResponse": {
            Error?: components["schemas"]["common.Error"];
            ResponseHeader?: components["schemas"]["common.ResponseHeader"];
            RoomTypes?: components["schemas"]["roomStatic_model.RoomTypeInfo"][];
        };
        "roomStatic_model.RoomTypeInfo": {
            BedTypeDesc?: string;
            BedTypeDescCN?: string;
            MaxOccupancy?: number;
            RoomTypeCode?: string;
            RoomTypeName?: string;
            RoomTypeNameCN?: string;
        };
        "searchOrder.OrderInfo": {
            /**
             * @description Agent reference ID;
             * @example 213415
             */
            AgentRefID?: string;
            /**
             * @description Currency code.
             * @example CNY
             */
            CurrencyCode?: string;
            /**
             * @description Hotel confirmation number.
             * @example 10470374
             */
            HotelConfirmationNo?: string;
            /**
             * @description Order status. <br><table><tr><th>OrderStatus</th><th>Description</th></tr><tr><td>PENDING</td><td>Booking confirmation pending.</td></tr><tr><td>CONFIRMED</td><td>Booking confirmed.</td></tr><tr><td>CANCELLED</td><td>Booking cancelled.</td></tr><tr><td>FAILED</td><td>Booking confirmation failed.</td></tr></table>
             * @example CANCELLED
             */
            OrderStatus?: string;
            /**
             * @description Tourmind order ID
             * @example 10470374
             */
            ReservationID?: string;
            /**
             * @description Total price of the booking.
             * @example 888.89
             */
            TotalPrice?: number;
            /**
             * @description Tourmind hotel ID.
             * @example 0
             */
            HotelCode?: number;
            /**
             * @description Number of rooms.
             * @example 0
             */
            RoomCount?: number;
            /**
             * @description Check-in date. Format YYYY-MM-DD.
             * @example 2020-01-01
             */
            CheckIn?: string;
            /**
             * @description Check-out date. Format YYYY-MM-DD.
             * @example 2020-01-02
             */
            CheckOut?: string;
            /** @description Room occupancy details with guest names. */
            PaxRooms?: components["schemas"]["createOrder.PaxRoom"][];
            /** @description Contact person name. */
            Contact?: string;
            /** @description Contact phone number. */
            ContactPhone?: string;
            /**
             * @description Booking creation time.
             * @example 2020-01-03 12:00:00
             */
            BookingTime?: string;
        };
        "searchOrder.OrderList": {
            /** @description List of orders. */
            OrderList?: components["schemas"]["searchOrder.OrderInfo"][];
            /**
             * @description Current page number.
             * @example 1
             */
            Page?: number;
            /**
             * @description Page size.
             * @example 50
             */
            PageSize?: number;
            /**
             * @description Total number of orders matching the query.
             * @example 100
             */
            Total?: number;
        };
        "searchOrder.QueryBookingsRequest": {
            /**
             * @description Date type for date range query. Possible values: CheckIn (check-in date), CheckOut (check-out date), Booking (booking date).
             * @example CheckIn
             */
            DateType: string;
            /**
             * @description Start date for the query range. Format YYYY-MM-DD. The date span (To minus From) must be <= 31 days.
             * @example 2024-01-01
             */
            From: string;
            /**
             * @description End date for the query range. Format YYYY-MM-DD. The date span (To minus From) must be <= 31 days.
             * @example 2024-01-31
             */
            To: string;
            /**
             * @description Page number for pagination. Must be >= 1.
             * @example 1
             */
            Page: number;
            /**
             * @description Number of results per page. Must be between 1 and 500.
             * @example 50
             */
            PageSize: number;
            RequestHeader: components["schemas"]["common.RequestHeader"];
        };
        "searchOrder.QueryBookingsResponse": {
            /** @description This value will be returned if an error occurs. */
            Error?: components["schemas"]["common.Error"];
            /** @description Paginated list of orders. Will not be returned if an error occurs. */
            OrderList?: components["schemas"]["searchOrder.OrderList"];
            ResponseHeader?: components["schemas"]["common.ResponseHeader"];
        };
        "searchOrder.QueryOrderRequest": {
            /**
             * @description Agent reference ID provided in the CreateOrder request; maximum length is 128.
             * @example 21345555
             */
            AgentRefID?: string;
            RequestHeader?: components["schemas"]["common.RequestHeader"];
        };
        "searchOrder.QueryOrderResponse": {
            /** @description This value will be returned if an error occurs. */
            Error?: components["schemas"]["common.Error"];
            /** @description This value will not be returned if an error occurs. */
            OrderInfo?: components["schemas"]["searchOrder.OrderInfo"];
            ResponseHeader?: components["schemas"]["common.ResponseHeader"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HotelDetail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Query parameters. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["hotelDetail.HotelDetailRequest"];
            };
        };
        responses: {
            /** @description Hotel details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["hotelDetail.HotelDetailResponse"];
                };
            };
            /** @description Application-level error envelope. The HTTP status is still 200; check Error.ErrorCode for the failure mode. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["common.Error"];
                };
            };
        };
    };
    CheckRoomRate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Query parameters. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["roomAvail.RoomAvailRequest"];
            };
        };
        responses: {
            /** @description Prebook */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["roomAvail.RoomAvailResponse"];
                };
            };
            /** @description Application-level error envelope. The HTTP status is still 200; check Error.ErrorCode for the failure mode. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["common.Error"];
                };
            };
        };
    };
    CreateOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Query parameters. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["createOrder.CreateOrderRequest"];
            };
        };
        responses: {
            /** @description Booking */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["createOrder.CreateOrderResponse"];
                };
            };
            /** @description Application-level error envelope. The HTTP status is still 200; check Error.ErrorCode for the failure mode. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["common.Error"];
                };
            };
        };
    };
    CancelOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Query parameters. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["cancelOrder.CancelOrderRequest"];
            };
        };
        responses: {
            /** @description Cancel */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["cancelOrder.CancelOrderResponse"];
                };
            };
            /** @description Application-level error envelope. The HTTP status is still 200; check Error.ErrorCode for the failure mode. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["common.Error"];
                };
            };
        };
    };
    SearchOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Query parameters. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["searchOrder.QueryOrderRequest"];
            };
        };
        responses: {
            /** @description Retrieve Booking */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["searchOrder.QueryOrderResponse"];
                };
            };
            /** @description Application-level error envelope. The HTTP status is still 200; check Error.ErrorCode for the failure mode. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["common.Error"];
                };
            };
        };
    };
    QueryBookings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Query parameters. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["searchOrder.QueryBookingsRequest"];
            };
        };
        responses: {
            /** @description Query Bookings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["searchOrder.QueryBookingsResponse"];
                };
            };
            /** @description Application-level error envelope. The HTTP status is still 200; check Error.ErrorCode for the failure mode. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["common.Error"];
                };
            };
        };
    };
    HotelStaticList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Query parameters. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["hotelstatic.HotelStaticListRequest"];
            };
        };
        responses: {
            /** @description Hotel static information. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["hotelstatic.HotelStaticListResponse"];
                };
            };
            /** @description Application-level error envelope. The HTTP status is still 200; check Error.ErrorCode for the failure mode. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["common.Error"];
                };
            };
        };
    };
    RegionList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Query parameters. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["regionList.RegionListRequest"];
            };
        };
        responses: {
            /** @description Region List */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["regionList.RegionListResponse"];
                };
            };
            /** @description Application-level error envelope. The HTTP status is still 200; check Error.ErrorCode for the failure mode. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["common.Error"];
                };
            };
        };
    };
    RoomTypeStatic: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Query parameters. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["roomStatic_model.RoomStaticRequest"];
            };
        };
        responses: {
            /** @description Hotel room data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["roomStatic_model.RoomStaticResponse"];
                };
            };
            /** @description Application-level error envelope. The HTTP status is still 200; check Error.ErrorCode for the failure mode. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["common.Error"];
                };
            };
        };
    };
}
